setup:
    prefix: 'j2s7s300_driver'
    model_filename: "jaco_dynamics"
    object_centers: {'HUMAN_CENTER': [-0.6,-0.55,0.0], 'LAPTOP_CENTER': [-0.7929,-0.1,0.0]}
    feat_list: ["efficiency", "table", "coffee"]
    feat_weights: [1.0,0.0,0.0]
    start: [283.3, 162.9, 360.1, 43.5, 265.3, 257.6, 288.0]
    goal: [360.4, 246.2, 365.9, 107.1, 180.1, 294.7, 253.0]
    goal_pose: [-0.62136, 0.01770, 0.30024]
    T: 20.0
    timestep: 0.5

planner:
    # These settings have been tuned for trajopt planner.
    type: "trajopt"
    max_iter: 50
    num_waypts: 5

controller:
    # These settings have been tuned for PID controller.
    type: "pid"
    p_gain: 50.0
    i_gain: 0.0
    d_gain: 20.0
    epsilon: 0.10
    max_cmd: 40.0

